const employees = [
  {
    id: 1,
    name: 'Karan',
    surname: 'Duffy',
    salary: 1010,
    workExperience: 10,
    isPrivileges: false,
    gender: 'male',
  },
  {
    id: 2,
    name: 'Brax',
    surname: 'Dalton',
    salary: 1200,
    workExperience: 12,
    isPrivileges: false,
    gender: 'male',
  },
  {
    id: 3,
    name: 'Jody',
    surname: 'Lam',
    salary: 480,
    workExperience: 3,
    isPrivileges: true,
    gender: 'female',
  },
  {
    id: 4,
    name: 'Ceara',
    surname: 'Zuniga',
    salary: 2430,
    workExperience: 20,
    isPrivileges: false,
    gender: 'female',
  },
  {
    id: 5,
    name: 'Walid',
    surname: 'Hulme',
    salary: 3150,
    workExperience: 30,
    isPrivileges: true,
    gender: 'female',
  },
  {
    id: 6,
    name: 'Hilary',
    surname: 'Oliver',
    salary: 1730,
    workExperience: 15,
    isPrivileges: false,
    gender: 'male',
  },
  {
    id: 7,
    name: 'Tye',
    surname: 'Herring',
    salary: 5730,
    workExperience: 45,
    isPrivileges: true,
    gender: 'male',
  },
  {
    id: 8,
    name: 'Marc',
    surname: 'Ellison',
    salary: 4190,
    workExperience: 39,
    isPrivileges: true,
    gender: 'male',
  },
  {
    id: 9,
    name: 'Deon',
    surname: 'Lindsay',
    salary: 790,
    workExperience: 7,
    isPrivileges: false,
    gender: 'male',
  },
  {
    id: 10,
    name: 'Marlene',
    surname: 'Rogers',
    salary: 5260,
    workExperience: 49,
    isPrivileges: true,
    gender: 'female',
  },
  {
    id: 11,
    name: 'Rodrigo',
    surname: 'Kouma',
    salary: 300,
    workExperience: 1,
    isPrivileges: false,
    gender: 'male',
  },
];
